Unitful.uconvert(u, evt::EventTime) = EventTime(uconvert(u, evt.value))
Unitful.uconvert(u, evt::Longitude) = Longitude(uconvert(u, evt.value))
Unitful.uconvert(u, evt::Latitude) = Latitude(uconvert(u, evt.value))
Unitful.uconvert(u, evt::Depth) = Depth(uconvert(u, evt.value))
# Unitful.uconvert(u::Unitful.FreeUnits, evtc::Depth) = Depth(uconvert(u, evtc.value))
